create database customer_behaviour;
select * from mytable;
SELECT COUNT(*) FROM customer_behaviour;
#--Q1. What is the total revenue generated by male vs. female customers?
select sum(purchase_amount)as revenue,gender 
from mytable
group by gender;
-#-Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from mytable
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from mytable);
#--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as avg_product_rating
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;
#--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;
#Q5 Do subscribed customers spend more Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       AVG(purchase_amount) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY avg_spend, total_revenue DESC;
#--Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
SELECT 
    item_purchased,
    SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    SUM(1) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100.0 / SUM(1) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
#--Q7. Segment customers into New, Returning, and Loyal based 
## on their total number of previous purchases, and show the count of each segment.
##(CTE)
with customer_type as(
select customer_id,previous_purchases,
CASE  
when previous_purchases = 1 then 'NEW'
when previous_purchases between 2 and 10 THEN 'Returning'
else  'Loyal'
end as customer_segment
from mytable
)
select customer_segment,count(*) as number_of_customer
from customer_type
group by customer_segment;
#--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, total_orders DESC;
#--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;
#--Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;
SHOW VARIABLES LIKE 'secure_file_priv';
SHOW COLUMNS FROM mytable;
SELECT
'customer_id','age','gender','item_purchased','category',
'purchase_amount','location','size','color','season',
'review_rating','subscription_status','shipping_type',
'discount_applied','previous_purchases','payment_method',
'frequency_of_purchases','age_group','purchase_frequency_days'
UNION ALL
SELECT
customer_id, age, gender, item_purchased, category,
purchase_amount, location, size, color, season,
review_rating, subscription_status, shipping_type,
discount_applied, previous_purchases, payment_method,
frequency_of_purchases, age_group, purchase_frequency_days
FROM mytable
INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/mytable_clean_2.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';





